apiVersion: apps/v1
kind: Deployment
metadata:
  name: PointContext
  labels:
    app: PointContext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PointContext
  template:
    metadata:
      labels:
        app: PointContext
    spec:
      containers:
        - name: PointContext
          image: username/PointContext:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5